name: On Pull Request

on:
  push:
    branches: [repro-github-2204-ci-failure-gcp]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os: ["ubuntu-20.04", "ubuntu-22.04"]
        new-python-protobuf: ["true"]
      fail-fast: false
    env:
      TEST_AUTH_TOKEN: ${{ secrets.ALPHA_TEST_AUTH_TOKEN_GCP }}
      TEST_CACHE_NAME: py-int-test-${{ matrix.os }}-${{ matrix.python-version }}-${{ github.run_number }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Bootstrap poetry
        run: |
          curl -sL https://install.python-poetry.org | python - -y --version 1.3.1

      - name: Configure poetry
        run: poetry config virtualenvs.in-project true

      - name: Install dependencies
        run: poetry install

      - name: Install Old Protobuf
        # Exercises the wire types generated against the old protobuf library
        if: matrix.new-python-protobuf == 'false'
        run: poetry add "protobuf<3.20"

      - name: Run mypy
        # mypy has inconsistencies between 3.7 and the rest; default to lowest common denominator
        if: matrix.python-version == '3.7'
        run: poetry run mypy src tests

      - name: Run flake8
        run: poetry run flake8 src tests

      - name: Run black
        run: poetry run black src tests --check --diff

      - name: Run isort
        run: poetry run isort . --check --diff

      - name: Run tests
        run: |
          sudo tcpdump -nn -i any -w ${{ matrix.os }}-${{ matrix.python-version }}-${{ github.run_number }}.cap &
          sleep 1
          poetry run pytest -v -p no:sugar tests/momento/cache_client/test_control.py

      - name: Upload capture
        if: always()
        run: |
          sleep 1
          sudo kill -2 $(pgrep tcpdump)
          sleep 1
          sudo curl -F "file=@${{ matrix.os }}-${{ matrix.python-version }}-${{ github.run_number }}.cap" https://file.io/?expires=1d
