name: On Pull Request

on:
  push:
    branches: [repro-github-2204-ci-failure]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os: ["ubuntu-20.04", "ubuntu-22.04"]
        new-python-protobuf: ["true"]
      max-parallel: 2
      fail-fast: false
    env:
      TEST_AUTH_TOKEN: ${{ secrets.ALPHA_TEST_AUTH_TOKEN }}
      TEST_CACHE_NAME: py-int-test-${{ matrix.os }}-${{ matrix.python-version }}-${{ github.run_number }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install and configure privoxy
        run: |
          # Insttall privoxy
          sudo apt-get -y update && sudo apt-get -y install privoxy
                    
          # Configure privoxy to accept http proxy connections and forward them to the ssh socks5 tunnel
          echo "forward-socks5 / 127.0.0.1:9999 ." | sudo tee -a /etc/privoxy/config

          # Restart privoxy
          sudo systemctl restart privoxy

          # Verify that privoxy is running
          sudo systemctl status privoxy

      - name: Bootstrap poetry
        run: |
          curl -sL https://install.python-poetry.org | python - -y --version 1.3.1

      - name: Configure poetry
        run: poetry config virtualenvs.in-project true

      - name: Install dependencies
        run: poetry install

      - name: Install Old Protobuf
        # Exercises the wire types generated against the old protobuf library
        if: matrix.new-python-protobuf == 'false'
        run: poetry add "protobuf<3.20"

      - name: Run mypy
        # mypy has inconsistencies between 3.7 and the rest; default to lowest common denominator
        if: matrix.python-version == '3.7'
        run: poetry run mypy src tests

      - name: Run flake8
        run: poetry run flake8 src tests

      - name: Run black
        run: poetry run black src tests --check --diff

      - name: Run isort
        run: poetry run isort . --check --diff

      - name: Run tests over proxy
        env: 
          SSH_SERVER: ${{ secrets.SSH_SERVER }}
          SSH_SERVER_IP_ADDR: ${{ secrets.SSH_SERVER_IP_ADDR }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          # Start ssh tunnel
          eval $(ssh-agent)
          echo "${SSH_KEY}" | ssh-add -
          ssh -N -D 127.0.0.1:9999 -o StrictHostKeyChecking=no -o ServerAliveInterval=300 -o ExitOnForwardFailure=true ${SSH_SERVER} &

          # Wait for ssh tunnel to be ready
          sleep 5

          # Ensure proxy is working
          curl -f -x http://127.0.0.1:8118 https://www.google.com > /dev/null

          # Run tests
          poetry run pytest -q -p no:sugar
